export const SEARCH_FILM = 'FILMS/SEARCH_FILM';
export const SELECT_FILM = 'FILMS/SELECT_FILM';
export const ADD_FILM_COMMENT = 'FILMS/ADD_FILM_COMMENT';
export const REMOVE_FILM_COMMENT = 'FILMS/REMOVE_FILM_COMMENT';
export const REMOVE_FILM_SELECTED = 'FILMS/REMOVE_FILM_SELECTED';
